services:
  server-service:
    build: afisha-server/.
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres-service
      - DB_NAME=main-service-db
      - DB_USER=omirkhon
      - DB_PASSWORD=123456
      - DB_PORT=5432
    depends_on:
      - postgres-service
      - statistics-service


  statistics-service:
    build: afisha-statistics/.
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres-service
      - DB_NAME=main-service-db
      - DB_USER=omirkhon
      - DB_PASSWORD=123456
      - DB_PORT=5432
    depends_on:
      - postgres-service

  postgres-service:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=main-service-db
      - POSTGRES_USER=omirkhon
      - POSTGRES_PASSWORD=123456